name: "\U0001F41E Bug report"
description: Report an issue with discord-fs
labels: ["\U0001F41E bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide as much information as possible that can help the maintainers reproduce the problem you ran into. If a report is vague (e.g. just a generic error message) and has no reproduction, it will receive a "need reproduction" label. If no reproduction is provided within a reasonable time-frame, the issue will be closed.
      placeholder: Reproduction
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: "Please include all applicable logs around the time this bug occurred. Optional if provided reproduction. Please try not to insert an image but copy paste the log text."
      render: shell
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Information about the system setup the error occurred on.
      render: shell
      placeholder: System (OS, CPU, Ram, ..), Software version, ..
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Select the severity of this issue
      options:
        - "\U0001F620 annoyance"
        - "\U0001F525 high"
        - "\U0001F4A5 critical"
    validations:
      required: true
